sonar.organization=smartflowmetering
sonar.projectKey=smartflowmetering_flakelab
sonar.projectName=FlakeLab
sonar.projectVersion=0.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=dist/**,.flakelab/**,node_modules/**
sonar.typescript.tsconfigPaths=tsconfig.json
